[package]
name = "smap"
description = "CLI tool to play a song at remote PC's speaker"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
publish.workspace = true

[workspace.package]
authors = ["haruki7049 <tontonkirikiri@gmail.com>"]
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/haruki7049/SMAP"
publish = false

[workspace.dependencies]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
rodio = "0.22.2"
thiserror = "2.0.18"
